# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Emoticon-Yahoo
version:      0.02
version_from: lib/Text/Emoticon/Yahoo.pm
installdirs:  site
requires:
    Test::More:                    0.32
    Text::Emoticon:                0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
